const routes = {
  APP_BASE_URL: '/poemix',
  ZINES_PATH: '/zines',
  BOOKS_PATH: '/livros',
  PROTESTIZANDO_PATH: '/protestizando',
  A_LER_VAZIOS_PATH: '/a_ler_vazios',
  PROTESTIZANDO_1_PATH: '/protestizando_1',
  PROTESTIZANDO_2_PATH: '/protestizando_2',
  PROTESTIZANDO_3_PATH: '/protestizando_3',
  PROTESTIZANDO_4_PATH: '/protestizando_4',
  PROTESTIZANDO_5_PATH: '/protestizando_5',
  PROTESTIZANDO_6_PATH: '/protestizando_6',
  PROTESTIZANDO_7_PATH: '/protestizando_7',
  PROTESTIZANDO_8_PATH: '/protestizando_8',
  PROTESTIZANDO_9_PATH: '/protestizando_9',
  PROTESTIZANDO_10_PATH: '/protestizando_10',
  PROTESTIZANDO_11_PATH: '/protestizando_11',
  PROTESTIZANDO_12_PATH: '/protestizando_12',
  PROTESTIZANDO_13_PATH: '/protestizando_13',
  PROTESTIZANDO_14_PATH: '/protestizando_14',
  PROTESTIZANDO_15_PATH: '/protestizando_15',
  PROTESTIZANDO_16_PATH: '/protestizando_16',
  PROTESTIZANDO_17_PATH: '/protestizando_17',
  PROTESTIZANDO_18_PATH: '/protestizando_18',
  PROTESTIZANDO_19_PATH: '/protestizando_19',
  PROTESTIZANDO_20_PATH: '/protestizando_20',
  PROTESTIZANDO_21_PATH: '/protestizando_21',
  PROTESTIZANDO_22_PATH: '/protestizando_22',
  PROTESTIZANDO_23_PATH: '/protestizando_23',
  PROTESTIZANDO_24_PATH: '/protestizando_24',
  PROTESTIZANDO_25_PATH: '/protestizando_25',
  PROTESTIZANDO_26_PATH: '/protestizando_26',
  PROTESTIZANDO_27_PATH: '/protestizando_27',
  PROTESTIZANDO_28_PATH: '/protestizando_28',
  PROTESTIZANDO_29_PATH: '/protestizando_29',
  PROTESTIZANDO_30_PATH: '/protestizando_30',
  PROTESTIZANDO_31_PATH: '/protestizando_31',
  PROTESTIZANDO_32_PATH: '/protestizando_32',
  PROTESTIZANDO_33_PATH: '/protestizando_33',
  PROTESTIZANDO_34_PATH: '/protestizando_34',
  PROTESTIZANDO_35_PATH: '/protestizando_35',
  PROTESTIZANDO_36_PATH: '/protestizando_36',
  PROTESTIZANDO_37_PATH: '/protestizando_37',
  PROTESTIZANDO_38_PATH: '/protestizando_38',
};

export const getRoutes = () => {
  return routes;
};
